apiVersion: batch/v1
kind: CronJob
metadata:
  name: fetch-vuln-definitions
  namespace: stackrox
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 0
          dnsPolicy: ClusterFirst
          serviceAccountName: vuln-loader
          restartPolicy: Never
          containers:
          - name: vuln-fetcher
            image: registry.access.redhat.com/ubi8/ubi:8.6
            resources: {}
            command:
            - /opt/fetchvulns.sh
            volumeMounts: 
            - name: scripts
              mountPath: /opt
          volumes:
          - name: scripts
            configMap:
              name: vulnfetcher
              defaultMode: 0555
