apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhacs-operator
  namespace: rhacs-operator 
spec:
  channel: stable 
  name: rhacs-operator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
  